### ISSUE TITLE
apf: functions not working in SERVICE blocks (Testing 0.9-DEV.2)

### ISSUE THREAD

**Issue by EmidioStani** [SPARQL-Anything/sparql.anything#421] opened 2023-11-08 18:01 UTC
Hello,

I have been using Sparql Anything Server 0.8.2 successfully for some data integration/transformation with: [https://github.com/SEMICeu/Taxonomy/blob/master/Entity_Legal_Form/SPARQL-query-for-ELF-v1.5.rq](https://github.com/SEMICeu/Taxonomy/tree/master/Entity_Legal_Form/SPARQL-query-for-ELF-v1.5.rq )

Now I wanted to test version 0.9-DEV.2 as I have seen string distances have been implemented.
However, when I run the same query I have 0 result (expected many ) and on the command line I see the below log messages:

[qtp1632789609-19] ERROR io.github.sparqlanything.engine.PropertyExtractor - Neither location nor content provided
[qtp1632789609-19] WARN io.github.sparqlanything.engine.FXWorkerOpService - No triplifier found
[qtp1632789609-19] ERROR io.github.sparqlanything.engine.PropertyExtractor - Neither location nor content provided
[qtp1632789609-19] WARN io.github.sparqlanything.engine.FXWorkerOpService - No triplifier found
[qtp1632789609-19] WARN org.apache.jena.sparql.engine.iterator.QueryIteratorCheck - Open iterator: QueryIterRoot/0
[qtp1632789609-19] WARN org.apache.jena.sparql.engine.iterator.QueryIteratorCheck - Open iterator: QueryIterFilterExpr/16
[qtp1632789609-19] WARN org.apache.jena.sparql.engine.iterator.QueryIteratorCheck - Open iterator: QueryIterFilterExpr/22
[qtp1632789609-19] WARN org.apache.jena.sparql.engine.iterator.QueryIteratorCheck - Open iterator: QueryIterNullIterator/23
[qtp1632789609-19] WARN org.apache.jena.sparql.engine.iterator.QueryIteratorCheck - Open iterator: QueryIterAssign/24
[qtp1632789609-19] INFO org.apache.jena.fuseki.Fuseki - [1] 200 OK (2.579 s)
[qtp1632789609-19] INFO org.apache.jena.fuseki.Request - [0:0:0:0:0:0:0:1] - - [08/Nov/2023:18:00:28 +0000] "GET /sparql.anything" 200 - "http://localhost:3000/sparql" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"

By the way, both show this error:
 ERROR org.apache.jena.util.JenaXMLInput - Problem setting StAX property - name: "http://javax.xml.XMLConstants/property/accessExternalDTD" - value: "" - error: Unrecognized property 'http://javax.xml.XMLConstants/property/accessExternalDTD'

Is there something I should do ?

Thanks,

Emidio

**Comment by EmidioStani** [comment] 2023-11-09 14:17
I have investigated a bit, it seems related to the jena [strSplit](https://jena.apache.org/documentation/query/library-propfunc.html) function I have used in my query:

    # split abbreviations delimited via ; character
    ?abbrs apf:strSplit(?abbrList ";") .
    BIND (IF(STRLEN(?abbrs) > 0, ?abbrs, 1/0) AS ?abbr) .
    ?abbrsTrans apf:strSplit(?abbrListTrans ";") .
    BIND (IF(STRLEN(?abbrsTrans) > 0, ?abbrsTrans, 1/0) AS ?abbrTrans) .

If I remove this part of query, it works. Are apf functions still supported via Sparql Anything ? If not, what alternative exist to split a string ?

**Comment by justin2004** [comment] 2023-11-09 16:55
@EmidioStani i believe you need to reference `apf:strSplit` outside of the sparql anything service clause. e.g.
```
select * where {
{service <x-sparql-anything:> { ... }}
{ ?abbrsTrans apf:strSplit(?abbrListTrans ";") }
...
```

**Comment by EmidioStani** [comment] 2023-11-09 17:57
Hello @justin2004 , as you can see:

https://github.com/SEMICeu/Taxonomy/blob/master/Entity_Legal_Form/SPARQL-query-for-ELF-v1.5.rq#L102

it is outside, it is on the WHERE block, and it works on 0.8.2 but it doesn't work on 0.9-DEV.2

**Comment by enridaga** [comment] 2023-11-10 09:28
Thanks for testing the current build, we knew there was an issue with apf functions inside the service block (#330) but now, apparently, this has scaled up. There have been quite a few changes in the way the system handles the execution; we need to figure this out before the next release.

**Comment by luigi-asprino** [comment] 2023-11-13 11:13
Hi, 

The problem is here https://github.com/SPARQL-Anything/sparql.anything/blob/75f63fddd35698726b671530d78044475357ac86/sparql-anything-engine/src/main/java/io/github/sparqlanything/engine/FacadeXOpExecutor.java#L59

The `apf:strSplit` is outside the service clause and is not encapsulated in FacadeXExecutionContext and will not be executed!
My fault.. will fix it in a moment.

**Comment by enridaga** [comment] 2023-11-13 11:18
Do you think the fix will also address #330?

**Comment by luigi-asprino** [comment] 2023-11-13 11:50
I re-open the issue because I didn't know that the  `Fix #<number of issue>` in the commit message closes the issue automatically.
@EmidioStani, I think that you should be able to use apf functions outside the service clauses. 
I reproduced the issue with this query

```
PREFIX fx: <http://sparql.xyz/facade-x/ns/>
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX apf: <http://jena.apache.org/ARQ/property#>
SELECT ?a WHERE {
    SERVICE <x-sparql-anything:> {
            fx:properties fx:content "abc;cde" .
            ?s rdf:_1 ?o
    }
    ?a apf:strSplit(?o ";") .
}
```

Let us know if it works.

> Do you think the fix will also address #330?

@enridaga, let me investigate a little bit more.

**Comment by enridaga** [comment] 2023-11-13 12:13
Can be tested with release https://github.com/SPARQL-Anything/sparql.anything/releases/tag/v0.9-DEV.3

**Comment by EmidioStani** [comment] 2023-11-13 13:58
Hello @luigi-asprino and @enridaga ,

I tested the same query with version 0.9-DEV.3 and it works, thanks for your work

**Comment by luigi-asprino** [comment] 2023-11-13 14:05
Great! I think we can close this now.

**Closed as completed by luigi-asprino** 2023-11-13 14:05 UTC
Labels: Bug
