### ISSUE TITLE
access file in zip: mixup absolute/relative url

### ISSUE THREAD

**Issue by VladimirAlexiev** [SPARQL-Anything/sparql.anything#335] opened 2023-01-26 15:22 UTC
This script (same as in #334) opens an archive (https://sparql-anything.readthedocs.io/en/latest/Configuration/#from-archive) and rdfizes files from it:
```sparql
### rdfize-zip.sparql
# rdfize an archive (zip) of files. parameter values:
# -v zip: zip filename or URL
# -v file: file regexp pattern (default ~.*~)
# sparql-anything -q ../rdfize-zip.sparql -v zip=graphql-2023-01-24.zip > raw-rdf.ttl

prefix bsdd: <http://bsdd.buildingsmart.org/def#>
prefix xyz:  <http://sparql.xyz/facade-x/data/>
prefix fx:   <http://sparql.xyz/facade-x/ns/>
prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd:  <http://www.w3.org/2001/XMLSchema#>

construct {
  ?s ?p ?o
} where {
  service <x-sparql-anything:> {
    bind(coalesce(?__file,".*") as ?pattern)
    fx:properties fx:location ?_zip.
    fx:properties fx:archive.matches ?pattern.
    [] fx:anySlot ?file
    service <x-sparql-anything:media-type=application/json> {
      bind(str(bsdd:) as ?bsdd)
      fx:properties fx:namespace ?bsdd.
      fx:properties fx:location ?file.
      fx:properties fx:from-archive ?_zip.
      fx:properties fx:use-rdfs-member true.
      ?s ?p ?o
    }
  }
}
```
fails with the following error:
```
[main] ERROR com.github.sparqlanything.engine.FacadeXOpExecutor - An error occurred: 
java.io.FileNotFoundException: 
tmp\cd81ed69fe4de812bb3928afd960e85d\http:\sparql.xyz\facade-x\ns\root 
(The filename, directory name, or volume label syntax is incorrect)

[main] ERROR com.github.sparqlanything.cli.SPARQLAnything - Iteration 1 failed with error: 
java.io.IOException: java.io.FileNotFoundException:
 tmp\cd81ed69fe4de812bb3928afd960e85d\http:\sparql.xyz\facade-x\ns\root 
(The filename, directory name, or volume label syntax is incorrect)
```
I see two problems here:
- forward slashes in `fx:` are replaced with backward slashes. Maybe that comes from Windows/Cygwin
- the absolute URL fx:root is appended to `tmp\cd81ed69fe4de812bb3928afd960e85d`: WHY?
  -  Notice that I set ` fx:namespace`, but to a different namespace: to rename `xyz -> bsdd` (BSDD is the data we're working with)

**Comment by VladimirAlexiev** [comment] 2023-01-26 15:44
This command causes the failure:
```
sparql-anything.bat -q ../scripts/rdfize-zip.sparql -v zip=graphql-2023-01-24.zip -v "file=\w+.json"
```

A script that merely finds and lists the files works ok:
```sparql
### list-zip.sparql
prefix xyz:  <http://sparql.xyz/facade-x/data/>
prefix fx:   <http://sparql.xyz/facade-x/ns/>
prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd:  <http://www.w3.org/2001/XMLSchema#>

select ?file
where {
  service <x-sparql-anything:> {
    bind(coalesce(?__file,".*") as ?pattern)
    fx:properties fx:location ?_zip.
    fx:properties fx:archive.matches ?pattern.
    [] fx:anySlot ?file
  }
}
```
Invoking it finds the right files:
```
# sparql-anything.bat -q ../scripts/list-zip.sparql -v zip=graphql-2023-01-24.zip -v "file=\w+.json"
file
countries.json
domains.json
languages.json
properties.json
reference_documents.json
units.json
```

**Comment by mihailradkov** [comment] 2023-01-27 07:36
This issue seems to be caused by `service <x-sparql-anything:media-type=application/json>`, more specifically by the `media-type` configuration. Removing it resolves the problem immediatelly. 
Not sure why this breaks the processing as the files are indeed JSONs.

**Comment by VladimirAlexiev** [comment] 2023-01-27 07:45
Which is even more puzzling since this simpler script that RDFizes a single file works ok.
This is the "inner loop" of the more complex script on top:
```sparql
### rdfize.sparql
# sparql-anything -q rdfize.sparql -v file=../samples/class-IfcWall.ELEMENTEDWALL.json
construct {
  ?s ?p ?o
} where {
  SERVICE <x-sparql-anything:media-type=application/json> {
    bind(str(bsdd:) as ?bsdd)
    fx:properties fx:namespace ?bsdd.
    fx:properties fx:location ?_file.
    fx:properties fx:use-rdfs-member true.
    ?s ?p ?o
  }
}
```

`tmp\cd81ed69fe4de812bb3928afd960e85d` is a folder where sparql-anything unzips the archive.
But why does it then append `http:\sparql.xyz\facade-x\ns\root ` instead of the file name it found?

PS: I've named the code excerpts for easier reference.

**Comment by enridaga** [comment] 2023-01-27 09:58
> But why does it then append http:\sparql.xyz\facade-x\ns\root  instead of the file name it found?

This looks like a bug

**Comment by luigi-asprino** [comment] 2023-02-08 17:00
The problem is the same as (or at least related to) the #334 
I close the issue so we can discuss a common solution on the #334 thread.

**Closed as completed by luigi-asprino** 2023-02-08 17:00 UTC
Labels: Bug
