### ISSUE TITLE
discussion: how about adding a streaming option?

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#135] opened 2021-10-25 12:39 UTC
I wonder how much effort it would be to alter the triplifiers so that they can can be configured to operate on a configurable amount of input at a time.

e.g. for csv files say you want to run your sparql query on 10 rows at a time but still combine the results into a single result set.

There is [interest](https://github.com/kg-construct/rml-questions/discussions/3#discussioncomment-1531237) in this feature.

**Comment by enridaga** [comment] 2021-11-04 09:26
> e.g. for CSV files say you want to run your SPARQL query on 10 rows at a time but still combine the results into a single result set.

This may be problematic because of partial and inconsistent results that may occur (e.g. joins having matching that span multiple groups would not be evaluated). Of course, one may think "who cares?" but then it is crucial that this feature is transparent to the developers (for example, adding a `slice=10` parameter to the CSV setting the number of rows to process on each iteration. However, I am not sure how a similar feature can help with nested structures -- e.g. JSON).

We started experimenting with streaming in this branch https://github.com/SPARQL-Anything/sparql.anything/tree/v0.1.0-DEV-strategy2 The plan is to pick this up and integrate it with the main branch, there are experiments to be conducted first, though.

A streaming version, in principle, should minimize RAM consumption but at the cost of either multiple I/O on the file or caching of intermediate results (on disk). This is harder to do than with RML engines because we are not generating triples here but we need at the same time to make them available for querying. For example, JOINs require to keep partial results somewhere... among other issues.

From the software engineering point of view, the current OO design does not seem to be easily adaptable to this approach. The difference is that, in the streaming-like approach, transformation needs to be performed during query execution, for each quad pattern requested to the DatasetGraph interface (which will be virtual). Therefore, the Triplifier should pass the data matching the pattern to an Iterator (the object to be returned). The problem is that the Triplifier interface is not doing that. Instead, it is populating a passed object with triples (the FXGraphBuilder). One of the reasons we postponed the integration is that I could not find a solution yet that would not require writing an alternative interface for Triplifier classes specifically for this strategy. Meaning twice the work for maintenance and evolution of triplifiers. But maybe this is not a big problem, considering this strategy only makes sense with formats that are used for very large datasets, so supporting only CSV, JSON, and XML is maybe sufficient?

**Comment by justin2004** [comment] 2021-11-04 19:43
> This may be problematic because of partial and inconsistent results that may occur (e.g. joins having matching that span multiple groups would not be evaluated).

When my team uses SPARQL Anything to triplify csv we know when we only need to see one row at a time. For large csv files we have been using [CSV2RDF](https://github.com/AtomGraph/CSV2RDF) so we don't have to do the batching ourselves.
You would only get inconsistent results if you wrote a query that depends on seeing more than one row at a time, right?

> However, I am not sure how a similar feature can help with nested structures -- e.g. JSON

One approach is to allow the user to specify a ~JSONPath expression that defines each slice that will be operated on.
e.g. (with jq)
```
cat aLarge.json | jq --compact-output '.entry[]'
```
which will put one json object per line.

But I think it might be more consistent to allow this slice expression to be SPARQL construct as well (but I think it might be simpler to implement with JSONPath).
And then an XPath expression could be used for xml/html.


> This is harder to do than with RML engines because we are not generating triples here but we need at the same time to make them available for querying.

I'll have to look at this more carefully later but this [line](https://github.com/AtomGraph/CSV2RDF/blob/5680ee0ec753bef927e6afbd4c53e99f67006374/src/main/java/com/atomgraph/etl/csv/stream/CSVStreamRDFProcessor.java#L81) might mean that CSV2RDF doesn't generate intermediate triples (to make them available for querying) like SPARQL Anything does but instead applies the query to each row (which is turned into a model).

So rowModel is initially "raw" then it is "constructed." Maybe?

**Comment by justin2004** [comment] 2021-11-04 20:01
related: https://github.com/AtomGraph/CSV2RDF/issues/7

**Comment by enridaga** [comment] 2021-11-16 16:05
I see two issues here:

- Streaming query execution: to reduce the impact on memory consumption (large files may hit memory limits)
- Slicing the input: in many cases, users may want to target a specific part of the input data, or execute a query on a collection of parts (e.g. executing a query on each row of the CSV). A slice parameter can accept a selector expression in some cases (JSON, XML, HTML). Unclear how such a feature should behave for other formats.

**Comment by enridaga** [comment] 2022-02-02 09:09
Slicing is being implemented in #21

**Comment by enridaga** [comment] 2022-08-03 15:06
I think we can close this one and resume the discussion on specific issues.

**Closed as completed by enridaga** 2022-08-03 15:06 UTC
