### ISSUE TITLE
Stability of the cosine distance

### ISSUE THREAD

**Issue by EmidioStani** [SPARQL-Anything/sparql.anything#423] opened 2023-11-10 08:30 UTC
Hello,

I have started to use release 0.9-DEV.2 (and 0.9-DEV.3) to compare string distances and it looks like the cosine distance, compared to the others, is not stable.
While the others report 0 to mean that strings are the same, the cosine distance returns a small number (positive or negative) from time to time, I would expect to be 0, see screenshot below:

<img width="844" alt="Screenshot 2023-11-10 092601" src="https://github.com/SPARQL-Anything/sparql.anything/assets/278367/f64a866f-1c17-42ef-8422-d75e203a13a3">

Does it happen to you as well ? 

Thanks,

Emidio

**Comment by luigi-asprino** [comment] 2023-11-13 14:51
Hi Emidio,

I haven't used the function much, but it seems that the problem is caused by the underlying implementation of the Cosine distance (which is from Apache Text common).

In fact, this

```
System.out.println(new CosineDistance().apply("Hong Kong", "Hong Kong"));
```

returns 2.220446049250313E-16

We can change the default cosine distance implementation by switching to that provided by the [string similarity library](https://github.com/tdebatty/java-string-similarity) which appears to work for the two examples (Hong Kong and Dominican Republic).

**Comment by EmidioStani** [comment] 2023-11-13 15:23
Thank you @luigi-asprino for investigating, I thought about it and I am surprised that this comes from the apache common library (I guess that should be well tested).

Would you please change it then to the other library ? I am willing to test it with the data I have

**Comment by luigi-asprino** [comment] 2023-11-13 15:25
Already done in [bebb1f7](https://github.com/SPARQL-Anything/sparql.anything/commit/bebb1f79620cd19e769dfb15a05abd5f0e213022).

You can test it with 0.9-DEV-5 https://github.com/SPARQL-Anything/sparql.anything/releases/tag/v0.9-DEV.5

**Comment by EmidioStani** [comment] 2023-11-13 16:42
Thank you @luigi-asprino ,

I tested with version v0.9-DEV-5 and it results stable now. I see also that QGram distance has been added.

**Comment by luigi-asprino** [comment] 2023-11-13 16:44
Great! Can we close the issue?

**Comment by EmidioStani** [comment] 2023-11-13 17:01
Yes, you can close it, thanks !

**Closed as completed** 2023-11-13 17:02 UTC
Labels: Bug
